#cpu
FROM pytorch/pytorch:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update
RUN apt upgrade -y

RUN apt install -y \
    git \
    build-essential \
    wget \
    unzip \
    pkg-config \
    cmake \
    pip \
    sudo \
    g++ \
    ca-certificates \
    htop \
    nano \
    libgl1-mesa-glx \
    gdal-bin \    
    python3-tk


RUN pip install -U sentence-transformers fastapi uvicorn transformers

COPY docker/app.py /home/app.py 


RUN useradd -m developer 

RUN echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer

USER developer


WORKDIR /home

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8001"]



